/*
 * hmi_dmm.c
 *
 *  Created on: 04 mar. 2023
 *      Author: Ludo
 */

#include "hmi_dmm.h"

#include "common_registers.h"
#include "dmm_registers.h"
#include "hmi_common.h"
#include "una.h"

/*** HMI DMM global variables ***/

const HMI_NODE_line_t HMI_DMM_LINE[HMI_DMM_LINE_INDEX_LAST] = {
    HMI_COMMON_LINE
    { "VRS =", HMI_NODE_DATA_TYPE_VOLTAGE, DMM_REGISTER_ADDRESS_ANALOG_DATA_1, DMM_REGISTER_ANALOG_DATA_1_MASK_VRS, DMM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "VHMI =", HMI_NODE_DATA_TYPE_VOLTAGE, DMM_REGISTER_ADDRESS_ANALOG_DATA_1, DMM_REGISTER_ANALOG_DATA_1_MASK_VHMI, DMM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "VUSB =", HMI_NODE_DATA_TYPE_VOLTAGE, DMM_REGISTER_ADDRESS_ANALOG_DATA_2, DMM_REGISTER_ANALOG_DATA_2_MASK_VUSB, DMM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "NODES_CNT =", HMI_NODE_DATA_TYPE_RAW_DECIMAL, DMM_REGISTER_ADDRESS_STATUS_1, DMM_REGISTER_STATUS_1_MASK_NODES_COUNT, DMM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "SC_PRD =", HMI_NODE_DATA_TYPE_TIME, DMM_REGISTER_ADDRESS_CONFIGURATION_0, DMM_REGISTER_CONFIGURATION_0_MASK_NODES_SCAN_PERIOD, DMM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "UL_PRD =", HMI_NODE_DATA_TYPE_TIME, DMM_REGISTER_ADDRESS_CONFIGURATION_0, DMM_REGISTER_CONFIGURATION_0_MASK_SIGFOX_UL_PERIOD, DMM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "DL_PRD =", HMI_NODE_DATA_TYPE_TIME, DMM_REGISTER_ADDRESS_CONFIGURATION_0, DMM_REGISTER_CONFIGURATION_0_MASK_SIGFOX_DL_PERIOD, DMM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE }
};
