/*
 * bcm.c
 *
 *  Created on: 29 mar. 2025
 *      Author: Ludo
 */

#include "hmi_bcm.h"

#include "bcm_registers.h"
#include "common_registers.h"
#include "hmi_common.h"
#include "una.h"

/*** BCM global variables ***/

const HMI_NODE_line_t HMI_BCM_LINE[HMI_BCM_LINE_INDEX_LAST] = {
    HMI_COMMON_LINE
    { "VSRC =", HMI_NODE_DATA_TYPE_VOLTAGE, BCM_REGISTER_ADDRESS_ANALOG_DATA_1, BCM_REGISTER_ANALOG_DATA_1_MASK_VSRC, BCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "VSTR =", HMI_NODE_DATA_TYPE_VOLTAGE, BCM_REGISTER_ADDRESS_ANALOG_DATA_1, BCM_REGISTER_ANALOG_DATA_1_MASK_VSTR, BCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "ISTR =", HMI_NODE_DATA_TYPE_CURRENT, BCM_REGISTER_ADDRESS_ANALOG_DATA_2, BCM_REGISTER_ANALOG_DATA_2_MASK_ISTR, BCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "VBKP =", HMI_NODE_DATA_TYPE_VOLTAGE, BCM_REGISTER_ADDRESS_ANALOG_DATA_2, BCM_REGISTER_ANALOG_DATA_2_MASK_VBKP, BCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "CHRG_EN =", HMI_NODE_DATA_TYPE_BIT, BCM_REGISTER_ADDRESS_STATUS_1, BCM_REGISTER_STATUS_1_MASK_CHENST, BCM_REGISTER_ADDRESS_CONTROL_1, BCM_REGISTER_CONTROL_1_MASK_CHEN },
    { "CHRG_ST0 =", HMI_NODE_DATA_TYPE_BIT, BCM_REGISTER_ADDRESS_STATUS_1, BCM_REGISTER_STATUS_1_MASK_CHRGST0, BCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "CHRG_ST1 =", HMI_NODE_DATA_TYPE_BIT, BCM_REGISTER_ADDRESS_STATUS_1, BCM_REGISTER_STATUS_1_MASK_CHRGST1, BCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "BKP_EN =", HMI_NODE_DATA_TYPE_BIT, BCM_REGISTER_ADDRESS_STATUS_1, BCM_REGISTER_STATUS_1_MASK_BKENST, BCM_REGISTER_ADDRESS_CONTROL_1, BCM_REGISTER_CONTROL_1_MASK_BKEN }
};
