/*
 * ddrm.c
 *
 *  Created on: 26 feb. 2023
 *      Author: Ludo
 */

#include "hmi_ddrm.h"

#include "common_registers.h"
#include "ddrm_registers.h"
#include "hmi_common.h"
#include "una.h"

/*** DDRM global variables ***/

const HMI_NODE_line_t HMI_DDRM_LINE[HMI_DDRM_LINE_INDEX_LAST] = {
    HMI_COMMON_LINE
    {"VIN =", HMI_NODE_DATA_TYPE_VOLTAGE, DDRM_REGISTER_ADDRESS_ANALOG_DATA_1, DDRM_REGISTER_ANALOG_DATA_1_MASK_INPUT_VOLTAGE, DDRM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    {"VOUT =", HMI_NODE_DATA_TYPE_VOLTAGE, DDRM_REGISTER_ADDRESS_ANALOG_DATA_1, DDRM_REGISTER_ANALOG_DATA_1_MASK_OUTPUT_VOLTAGE, DDRM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    {"IOUT =", HMI_NODE_DATA_TYPE_CURRENT, DDRM_REGISTER_ADDRESS_ANALOG_DATA_2, DDRM_REGISTER_ANALOG_DATA_2_MASK_OUTPUT_CURRENT, DDRM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    {"DCDC =", HMI_NODE_DATA_TYPE_BIT, DDRM_REGISTER_ADDRESS_STATUS_1, DDRM_REGISTER_STATUS_1_MASK_RCS, DDRM_REGISTER_ADDRESS_CONTROL_1, DDRM_REGISTER_CONTROL_1_MASK_REN }
};
