/*
 * bcm.c
 *
 *  Created on: 29 mar. 2025
 *      Author: Ludo
 */

#include "hmi_bcm.h"

#include "bcm_registers.h"
#include "common_registers.h"
#include "hmi_common.h"
#include "una.h"

/*** BCM global variables ***/

const HMI_NODE_line_t HMI_BCM_LINE[HMI_BCM_LINE_INDEX_LAST] = {
    HMI_COMMON_LINE
    { "VSRC =", HMI_NODE_DATA_TYPE_VOLTAGE, BCM_REGISTER_ADDRESS_ANALOG_DATA_1, BCM_REGISTER_ANALOG_DATA_1_MASK_SOURCE_VOLTAGE, BCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "VSTR =", HMI_NODE_DATA_TYPE_VOLTAGE, BCM_REGISTER_ADDRESS_ANALOG_DATA_1, BCM_REGISTER_ANALOG_DATA_1_MASK_STORAGE_VOLTAGE, BCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "ISTR =", HMI_NODE_DATA_TYPE_CURRENT, BCM_REGISTER_ADDRESS_ANALOG_DATA_2, BCM_REGISTER_ANALOG_DATA_2_MASK_CHARGE_CURRENT, BCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "VBKP =", HMI_NODE_DATA_TYPE_VOLTAGE, BCM_REGISTER_ADDRESS_ANALOG_DATA_2, BCM_REGISTER_ANALOG_DATA_2_MASK_BACKUP_VOLTAGE, BCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "CHRG =", HMI_NODE_DATA_TYPE_BIT, BCM_REGISTER_ADDRESS_STATUS_1, BCM_REGISTER_STATUS_1_MASK_CHCS, BCM_REGISTER_ADDRESS_CONTROL_1, BCM_REGISTER_CONTROL_1_MASK_CHEN },
    { "CHST0 =", HMI_NODE_DATA_TYPE_BIT, BCM_REGISTER_ADDRESS_STATUS_1, BCM_REGISTER_STATUS_1_MASK_CHST0, BCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "CHST1 =", HMI_NODE_DATA_TYPE_BIT, BCM_REGISTER_ADDRESS_STATUS_1, BCM_REGISTER_STATUS_1_MASK_CHST1, BCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "BKP =", HMI_NODE_DATA_TYPE_BIT, BCM_REGISTER_ADDRESS_STATUS_1, BCM_REGISTER_STATUS_1_MASK_BKCS, BCM_REGISTER_ADDRESS_CONTROL_1, BCM_REGISTER_CONTROL_1_MASK_BKEN }
};
