/*
 * r4s8cr.c
 *
 *  Created on: 05 feb. 2023
 *      Author: Ludo
 */

#include "hmi_r4s8cr.h"

#include "hmi_common.h"
#include "r4s8cr_registers.h"
#include "una.h"

/*** R4S8CR global variables ***/

const HMI_NODE_line_t HMI_R4S8CR_LINE[HMI_R4S8CR_LINE_INDEX_LAST] = {
	{ "RELAY 1 =", HMI_NODE_DATA_TYPE_BIT, R4S8CR_REGISTER_ADDRESS_STATUS, R4S8CR_REGISTER_STATUS_MASK_R1STST, R4S8CR_REGISTER_ADDRESS_CONTROL, R4S8CR_REGISTER_CONTROL_MASK_R1ST },
	{ "RELAY 2 =", HMI_NODE_DATA_TYPE_BIT, R4S8CR_REGISTER_ADDRESS_STATUS, R4S8CR_REGISTER_STATUS_MASK_R2STST, R4S8CR_REGISTER_ADDRESS_CONTROL, R4S8CR_REGISTER_CONTROL_MASK_R2ST },
	{ "RELAY 3 =", HMI_NODE_DATA_TYPE_BIT, R4S8CR_REGISTER_ADDRESS_STATUS, R4S8CR_REGISTER_STATUS_MASK_R3STST, R4S8CR_REGISTER_ADDRESS_CONTROL, R4S8CR_REGISTER_CONTROL_MASK_R3ST },
	{ "RELAY 4 =", HMI_NODE_DATA_TYPE_BIT, R4S8CR_REGISTER_ADDRESS_STATUS, R4S8CR_REGISTER_STATUS_MASK_R4STST, R4S8CR_REGISTER_ADDRESS_CONTROL, R4S8CR_REGISTER_CONTROL_MASK_R4ST },
	{ "RELAY 5 =", HMI_NODE_DATA_TYPE_BIT, R4S8CR_REGISTER_ADDRESS_STATUS, R4S8CR_REGISTER_STATUS_MASK_R5STST, R4S8CR_REGISTER_ADDRESS_CONTROL, R4S8CR_REGISTER_CONTROL_MASK_R5ST },
	{ "RELAY 6 =", HMI_NODE_DATA_TYPE_BIT, R4S8CR_REGISTER_ADDRESS_STATUS, R4S8CR_REGISTER_STATUS_MASK_R6STST, R4S8CR_REGISTER_ADDRESS_CONTROL, R4S8CR_REGISTER_CONTROL_MASK_R6ST },
	{ "RELAY 7 =", HMI_NODE_DATA_TYPE_BIT, R4S8CR_REGISTER_ADDRESS_STATUS, R4S8CR_REGISTER_STATUS_MASK_R7STST, R4S8CR_REGISTER_ADDRESS_CONTROL, R4S8CR_REGISTER_CONTROL_MASK_R7ST },
	{ "RELAY 8 =", HMI_NODE_DATA_TYPE_BIT, R4S8CR_REGISTER_ADDRESS_STATUS, R4S8CR_REGISTER_STATUS_MASK_R8STST, R4S8CR_REGISTER_ADDRESS_CONTROL, R4S8CR_REGISTER_CONTROL_MASK_R8ST },
};
