/*
 * mpmcm.c
 *
 *  Created on: 26 feb. 2023
 *      Author: Ludo
 */

#include "hmi_mpmcm.h"

#include "common_registers.h"
#include "hmi_common.h"
#include "mpmcm_registers.h"
#include "una.h"

/*** MPMCM global variables ***/

const HMI_NODE_line_t HMI_MPMCM_LINE[HMI_MPMCM_LINE_INDEX_LAST] = {
    HMI_COMMON_LINE
    { "VRMS =",  HMI_NODE_DATA_TYPE_VOLTAGE, MPMCM_REGISTER_ADDRESS_CH1_RMS_VOLTAGE_0, MPMCM_REGISTER_MASK_RUN, MPMCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "FREQ = ", HMI_NODE_DATA_TYPE_FREQUENCY, MPMCM_REGISTER_ADDRESS_MAINS_FREQUENCY_0, MPMCM_REGISTER_MASK_RUN, MPMCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "PACT1 =", HMI_NODE_DATA_TYPE_ACTIVE_POWER, MPMCM_REGISTER_ADDRESS_CH1_ACTIVE_POWER_0, MPMCM_REGISTER_MASK_RUN, MPMCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "PAPP1 =", HMI_NODE_DATA_TYPE_APPARENT_POWER, MPMCM_REGISTER_ADDRESS_CH1_APPARENT_POWER_0, MPMCM_REGISTER_MASK_RUN, MPMCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "PACT2 =", HMI_NODE_DATA_TYPE_ACTIVE_POWER, MPMCM_REGISTER_ADDRESS_CH2_ACTIVE_POWER_0, MPMCM_REGISTER_MASK_RUN, MPMCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "PAPP2 =", HMI_NODE_DATA_TYPE_APPARENT_POWER, MPMCM_REGISTER_ADDRESS_CH2_APPARENT_POWER_0, MPMCM_REGISTER_MASK_RUN, MPMCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "PACT3 =", HMI_NODE_DATA_TYPE_ACTIVE_POWER, MPMCM_REGISTER_ADDRESS_CH3_ACTIVE_POWER_0, MPMCM_REGISTER_MASK_RUN, MPMCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "PAPP3 =", HMI_NODE_DATA_TYPE_APPARENT_POWER, MPMCM_REGISTER_ADDRESS_CH3_APPARENT_POWER_0, MPMCM_REGISTER_MASK_RUN, MPMCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "PACT4 =", HMI_NODE_DATA_TYPE_ACTIVE_POWER, MPMCM_REGISTER_ADDRESS_CH4_ACTIVE_POWER_0, MPMCM_REGISTER_MASK_RUN, MPMCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "PAPP4 =", HMI_NODE_DATA_TYPE_APPARENT_POWER, MPMCM_REGISTER_ADDRESS_CH4_APPARENT_POWER_0, MPMCM_REGISTER_MASK_RUN, MPMCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "PACT5 =", HMI_NODE_DATA_TYPE_ACTIVE_POWER, MPMCM_REGISTER_ADDRESS_TIC_ACTIVE_POWER_0, MPMCM_REGISTER_MASK_RUN, MPMCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
    { "PAPP5 =", HMI_NODE_DATA_TYPE_APPARENT_POWER, MPMCM_REGISTER_ADDRESS_TIC_APPARENT_POWER_0, MPMCM_REGISTER_MASK_RUN, MPMCM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
};
