/*
 * lvrm.c
 *
 *  Created on: 22 jan. 2023
 *      Author: Ludo
 */

#include "hmi_lvrm.h"

#include "common_registers.h"
#include "hmi_common.h"
#include "lvrm_registers.h"
#include "una.h"

/*** LVRM global variables ***/

const HMI_NODE_line_t HMI_LVRM_LINE[HMI_LVRM_LINE_INDEX_LAST] = {
    HMI_COMMON_LINE
	{ "VCOM =", HMI_NODE_DATA_TYPE_VOLTAGE, LVRM_REGISTER_ADDRESS_ANALOG_DATA_1, LVRM_REGISTER_ANALOG_DATA_1_MASK_VCOM, LVRM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
	{ "VOUT =", HMI_NODE_DATA_TYPE_VOLTAGE, LVRM_REGISTER_ADDRESS_ANALOG_DATA_1, LVRM_REGISTER_ANALOG_DATA_1_MASK_VOUT, LVRM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
	{ "IOUT =", HMI_NODE_DATA_TYPE_CURRENT, LVRM_REGISTER_ADDRESS_ANALOG_DATA_2, LVRM_REGISTER_ANALOG_DATA_2_MASK_IOUT, LVRM_REGISTER_ADDRESS_CONTROL_1, UNA_REGISTER_MASK_NONE },
	{ "RELAY =", HMI_NODE_DATA_TYPE_BIT, LVRM_REGISTER_ADDRESS_STATUS_1,  LVRM_REGISTER_STATUS_1_MASK_RLSTST, LVRM_REGISTER_ADDRESS_CONTROL_1, LVRM_REGISTER_CONTROL_1_MASK_RLST },
	{ "ZCCT =", HMI_NODE_DATA_TYPE_BIT, LVRM_REGISTER_ADDRESS_CONTROL_1, LVRM_REGISTER_CONTROL_1_MASK_ZCCT, LVRM_REGISTER_ADDRESS_CONTROL_1, LVRM_REGISTER_CONTROL_1_MASK_ZCCT }
};
