/*
 * dinfox.h
 *
 *  Created on: 12 nov 2022
 *      Author: Ludo
 */

#ifndef __DINFOX_H__
#define __DINFOX_H__

#include "node_common.h"
#include "types.h"

/*** DINFOX macros ***/

#define DINFOX_COMMON_DATA_NAME		"HW =", "SW =", "RESET =", "TMCU =", "VMCU ="
#define DINFOX_COMMON_DATA_UNIT		STRING_NULL, STRING_NULL, STRING_NULL, "|C", "mV"
#define DINFOX_DATA_ERROR			"ERROR"
#define DINFOX_STRING_BUFFER_SIZE	16
#define DINFOX_RS485_TIMEOUT_MS		100

/*** DINFOX boards identifier ***/

typedef enum {
	DINFOX_BOARD_ID_LVRM = 0,
	DINFOX_BOARD_ID_BPSM,
	DINFOX_BOARD_ID_DDRM,
	DINFOX_BOARD_ID_UHFM,
	DINFOX_BOARD_ID_GPSM,
	DINFOX_BOARD_ID_SM,
	DINFOX_BOARD_ID_DIM,
	DINFOX_BOARD_ID_RRM,
	DINFOX_BOARD_ID_DMM,
	DINFOX_BOARD_ID_MPMCM,
	DINFOX_BOARD_ID_LAST,
	DINFOX_BOARD_ID_ERROR
} DINFOX_board_id_t;

/*** DINFOX common registers set ***/

typedef enum {
	DINFOX_REGISTER_RS485_ADDRESS = 0,
	DINFOX_REGISTER_BOARD_ID,
	DINFOX_REGISTER_HW_VERSION_MAJOR,
	DINFOX_REGISTER_HW_VERSION_MINOR,
	DINFOX_REGISTER_SW_VERSION_MAJOR,
	DINFOX_REGISTER_SW_VERSION_MINOR,
	DINFOX_REGISTER_SW_VERSION_COMMIT_INDEX,
	DINFOX_REGISTER_SW_VERSION_COMMIT_ID,
	DINFOX_REGISTER_SW_VERSION_DIRTY_FLAG,
	DINFOX_REGISTER_RESET,
	DINFOX_REGISTER_ERROR_STACK,
	DINFOX_REGISTER_TMCU_DEGREES,
	DINFOX_REGISTER_VMCU_MV,
	DINFOX_REGISTER_LAST
} DINFOX_common_registers_t;

/*** DINFOX common data index ***/

typedef enum {
	DINFOX_DATA_INDEX_HW_VERSION = 0,
	DINFOX_DATA_INDEX_SW_VERSION,
	DINFOX_DATA_INDEX_RESET_FLAG,
	DINFOX_DATA_INDEX_TMCU_DEGREES,
	DINFOX_DATA_INDEX_VMCU_MV,
	DINFOX_DATA_INDEX_LAST
} DINFOX_common_data_index_t;

/*** DINFOX functions ***/

NODE_status_t DINFOX_read_data(RS485_address_t rs485_address, DINFOX_common_data_index_t data_index, char_t* data_value_ptr, uint8_t* data_value_size);

#endif /* __DINFOX_H__ */
